# file: roles/kafka/tasks/kafka_install.yml

- name: ensure kafka local working directory is present
  file: path={{ kafka_local_dir }} owner={{ kafka_user }} group={{ kafka_group }} mode=0750 state=directory

- name: ensure kafka supervisor log directory is present
  file: path={{ kafka_supervisor_log_dir }} mode=0755 state=directory

- name: copy over and unarchive kafka tarball
  unarchive: src={{ kafka_tgz }} dest={{ kafka_local_dir }}

- name: ensure symlink for latest version is present
  file: path={{ kafka_home }} src={{ kafka_raw_home }} state=link force=yes

- name: ensure kafka log directories are present
  file: path={{ item }} owner={{ kafka_user }} group={{ kafka_group }} mode=0750 state=directory
  with_items: kafka_log_dirs

- name: update kafka install permissions
  file: path={{ kafka_raw_home }} owner={{ kafka_user }} group={{ kafka_group }} state=directory recurse=yes

