# file: roles/pcapy/tasks/pcapy_install_tasks.yml (main.yml)

# ------------------------------------------------------------
# Build pcapy extension module

- name: Install libpcap
  include: libpcap_install.yml
  when: ansible_os_family != "Darwin"

- name: Copy over pcapy and unpack
  unarchive: src={{ pcapy_pyext_tgz }} dest={{ dependencies_root }}

- name: Build pcapy extension
  shell: "{{ pydist_build_ext_default }}"
  args:
    chdir: "{{ pcapy_pyext_unarc }}"

