# file: roles/kafka/defaults/kafka_main_vars.yml (main.yml)

# kafka_repo_url: https://github.com/apache/kafka.git
# kafka_version: 0.8.2
kafka_user: kafka
kafka_group: kafka
kafka_local_dir: /opt/kafka
kafka_log_dirs:
  - /storage/hadoop-data1/kafka/log
  - /storage/hadoop-data2/kafka/log
  - /storage/hadoop-data3/kafka/log
  - /storage/hadoop-data4/kafka/log

kafka_supervisor_log_dir: /var/log/kafka

kafka_tgz: kafka_2.11-0.8.2.0.tgz
kafka_unarc: kafka_2.11-0.8.2.0
kafka_raw_home: "{{ kafka_local_dir }}/{{ kafka_unarc }}"
kafka_home: "{{ kafka_local_dir }}/latest"
kafka_user_home: "{{ kafka_local_dir }}/home"
kafka_bin: "{{ kafka_home }}/bin"
kafka_config: "{{ kafka_home }}/config"
kafka_config_server_properties: "{{ kafka_config }}/server.properties"

# server.properties required settings
kafka_server_JMX_PORT: 13005
kafka_server_broker_id: 1
kafka_server_port: 9092
kafka_host_name: localhost
kafka_server_zookeeper_connect:
  - node2:2181
  - node3:2181
  - node4:2181
kafka_server_num_partitions: 1

# server.properties advanced settings
kafka_server_num_network_threads: 2
kafka_server_num_io_threads: 2
kafka_server_socket_send_buffer_bytes: 1048576
kafka_server_socket_receive_buffer_bytes: 1048576
kafka_server_socket_request_max_bytes: 1048576
kafka_server_log_flush_interval_messages: 10000
kafka_server_log_flush_interval_ms: 10000
kafka_server_log_retention_hours: 168
kafka_server_log_segment_bytes: 536870912
kafka_server_log_cleanup_interval_mins: 1
kafka_server_zookeeper_connection_timeout_ms: 1000000
kafka_server_kafka_metrics_polling_interval_secs: 5
kafka_server_kafka_metrics_reporters: kafka.metrics.KafkaCSVMetricsReporter
kafka_server_kafka_csv_metrics_reporter_enabled: "false"

kafka_heap_size: 30g

kafka_supervisor_command_env_settings:
  - "JAVA_HOME={{ java_home }}"
  - "JMX_PORT={{kafka_server_JMX_PORT}}"
  - 'KAFKA_HEAP_OPTS="-Xmx{{ kafka_heap_size }} -Xms{{ kafka_heap_size }}"'
kafka_supervisor_command: "env {{ kafka_supervisor_command_env_settings|join(' ') }}  {{kafka_bin}}/kafka-server-start.sh {{kafka_config_server_properties}}"
