# file: roles/commons/tasks/common_main_tasks.yml

# Used as a dependency for other roles with the "scape_distro"
# variable set (e.g. development and production roles)

# - name: Ensure {{ scape_group }} group exists
#   group: name=scape state=present
#   sudo: yes

# - name: Ensure Scape admins are in {{ scape_group }} group
#   user: name={{ item }} groups={{ scape_group }} append=yes
#   with_items: scape_admins

- debug: var=scape_root_need_sudo

- name: Ensure Scape root directory exists
  file: dest={{ scape_root }} owner={{ scape_user }} state=directory
  ignore_errors: true
  
- name: Ensure Scape distro root directory exists
  file: dest={{ scape_distro_root }} owner={{ scape_user }} state=directory
  ignore_errors: true

- name: Ensure Scape system directories exist
  file: dest={{ item }} owner={{ scape_user }} state=directory
  with_items: scape_system_dirs
  ignore_errors: true

  
