# file: roles/elasticsearch/tasks/elasticsearch_install.yml

- name: ensure elasticsearch local working directory is present
  file: path={{ elasticsearch_local_dir }} owner={{ elasticsearch_user }} group={{ elasticsearch_group }} mode=0750 state=directory

- name: ensure elasticsearch supervisor log directory is present
  file: path={{ elasticsearch_supervisor_log_dir }} mode=0755 state=directory

- name: copy over and unarchive elasticsearch tarball
  unarchive: src={{ elasticsearch_tgz }} dest={{ elasticsearch_local_dir }}

- name: ensure symlink for latest version is present
  file: path={{ elasticsearch_home }} src={{ elasticsearch_raw_home }} state=link force=yes

- name: ensure elasticsearch data directories are present
  file: path={{ item }} owner={{ elasticsearch_user }} group={{ elasticsearch_group }} mode=0750 state=directory
  with_items: elasticsearch_data_dirs

- name: update elasticsearch install permissions
  file: path={{ elasticsearch_raw_home }} owner={{ elasticsearch_user }} group={{ elasticsearch_group }} state=directory recurse=yes

