# file: roles/elaticsearch/tasks/configure.yml

- name: Make sure the config directory exists
  file: path={{ elasticsearch_path_conf }} state=directory owner={{ elasticsearch_user }} group={{ elasticsearch_group }} mode=0755

- name: Update the elasticsearch configuration
  template: src=opt_elasticsearch_latest_config_elasticsearch.yml.j2 dest={{ elasticsearch_config_elasticsearch_yml }} owner={{ elasticsearch_user }} group={{ elasticsearch_group }} mode=0644
  notify:
    - restart supervisor
