# file: roles/elasticsearch/tasks/elasticsearch_user.yml

- name: Make sure the elasticsearch group is present
  action: group name={{ elasticsearch_group }} state=present #  gid={{ elasticsearch_gid }}

- name: Make sure the elasticsearch user directory is present
  action: file path={{ elasticsearch_user_home }} state=directory

- name: Make sure the elasticsearch user is present
  user: name={{ elasticsearch_user }} group={{ elasticsearch_group }} home={{ elasticsearch_user_home }} shell=/bin/bash state=present comment="elasticsearch user" # uid=$elasticsearch_uid 

- name: Set the right elasticsearch user directory permissions
  action: file path={{ elasticsearch_user_home }} owner={{ elasticsearch_user }} group={{ elasticsearch_group }} mode=0755 state=directory

- name: Set the right expiration on the elasticsearch user
  command: "sudo chage -I -1 -E -1 -m -1 -M -1 -W -1 -E -1 {{ elasticsearch_user }}"

- name: Add limits.conf for elasticsearch user
  template:
    src: etc_security_limits.d_100-elasticsearch.conf.j2
    dest: /etc/security/limits.d/100-elasticsearch.conf
  tags:
    - elasticsearch_ulimit