# file: roles/dnet/tasks/dnet_install_tasks.yml

# ------------------------------------------------------------
# Build base dnet lib
- name: Copy over dnet lib and unpack
  unarchive: src={{ dnet_lib_tgz }} dest={{ dependencies_root }}
  args:
    creates: "{{ dnet_lib_unarc }}"

- name: Build dnet lib
  shell: "{{ item }}"
  args:
    chdir: "{{ dnet_lib_unarc }}"
  with_items:
    - "./configure --prefix={{ scape_distro_root|quote }}"
    - make install
    
# ------------------------------------------------------------
# Build base Maxmind dnet lib

# 
# XXXX Needs Fix XXXXX
# 
# The dnet build process can't seem to handle the "pip install ."
# option. So, have to fall back on setup.py install.
- name: Build dnet Python extension
  shell: "{{ pydist_build_ext_setup_py_build_ext }} && python setup.py install"
  args:
    chdir: "{{ dnet_pyext_path }}"
