# file: roles/anaconda/tasks/anaconda_fix_readline_tasks.yml
# https://github.com/ContinuumIO/anaconda-issues/issues/42#issuecomment-63388575

- name: remove existing readline module
  shell: "{{ pydist_activate }} && conda remove readline --yes"
  ignore_errors: True

- name: remove existing readline.so
  file: dest="{{ pydist_lib }}/python2.7/lib-dynload/readline.so" state=absent

- name: copy over new readline module
  copy: src={{ anaconda_readline_tgz }} dest={{ anaconda_readline_install_path }}

- name: install new readline
  shell: '{{ pydist_activate }} && pip install {{ anaconda_readline_install_path }} --global-option="build_ext" --global-option="{{ pydist_build_ext_library_dirs }}" --global-option="{{ pydist_build_ext_include_dirs }}"'

- name: Touch linux readline fix sentenel file
  file: dest={{ anaconda_linux_readline_fix_sentinel }} state=touch
  
