# file: roles/thrift/tasks/thrift_install_tasks.yml

# ------------------------------------------------------------
# Build base thrift lib

- name: Copy over thrift and unpack
  unarchive: src={{ thrift_pyext_tgz }} dest={{ dependencies_root }}

- name: Build thrift extension
  shell: "{{ pydist_build_ext_default }}"
  args:
    chdir: "{{ thrift_pyext_unarc }}"

- name: Verify existence of thrift module
  shell: "{{ pydist_activate }} && python -c 'import thrift'"

