# file: roles/geoip2/tasks/geoip2_main_tasks.yml (main.yml)

- name: Check for existence of geoip2 Python module
  shell: "{{ pydist_activate }} && python -c 'import geoip2'"
  register: geoip2_import
  ignore_errors: True

- include: geoip2_install_tasks.yml
  when: (geoip2_import.rc != 0) or dependencies_reinstall
  
- name: Ensure existence of geoip2 db directory
  file: dest={{ geoip2_db_path }} owner={{ scape_user }} state=directory

- name: Copy GeoLite2-City.mmdb.gz
  copy: src={{ geoip2_db_gz }} dest="{{ geoip2_db_path }}/{{ geoip2_db_gz }}"

- name: Unarchvie GeoLite2-City.mmdb.gz
  shell: "gunzip -c {{ geoip2_db_gz }} > {{ geoip2_db_unarc }}"
  args:
    chdir: "{{ geoip2_db_path }}"
    creates: "{{ geoip2_db_path }}/{{ geoip2_db_unarc }}"
    
