# file: roles/kafka/meta/kafka_main_meta.yml (main.yml)

dependencies:
#   - { role: hostname }
#   - { role: build }
#   - { role: python }
#   - { role: jdk }
#   - { role: scala }
#   - { role: maven }
  - { role: supervisor }
