# file: roles/jcc/tasks/jcc_install_tasks.yml

# ------------------------------------------------------------
# Build base jcc lib
#
# Mystery solved:
# http://stackoverflow.com/a/26960808/1869370
# 
# On 10.8.5 Macs, jcc refused to build, throwing an inscrutable "atom
# not found in symbolIndex" error (so much for LLVM having "clearer
# errors"). Finally found the above link suggesting setting the
# NO_SHARED env var, which fixed the error. 

- name: Copy over jcc and unpack
  unarchive: src={{ jcc_pyext_tgz }} dest={{ dependencies_root }}

- name: Build jcc extension
  shell: "{{ pydist_activate }} && export JAVA_HOME={{ java_home }} && export JCC_JDK={{ jcc_jdk }} && export NO_SHARED=1 && {{ java_activate }} && {{ pydist_build_ext_default }}"
  args:
    chdir: "{{ jcc_pyext_unarc }}"


