# file: roles/jcc/tasks/jcc_main_tasks.yml (main.yml)

- name: Check for existence of jcc Python module
  shell: "{{ pydist_activate }} && python -c 'import jcc'"
  register: jcc_import
  ignore_errors: True

- include: jcc_install_tasks.yml
  when: (jcc_import.rc != 0) or dependencies_reinstall
  