"""
Copyright (2016) Massachusetts Institute of Technology.  Reproduction/Use 
of all or any part of this material shall acknowledge the MIT Lincoln 
Laboratory as the source under the sponsorship of the US Air Force 
Contract No. FA8721-05-C-0002.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

"""
PROTOCOLS = \
    {0: ('hopopt', 'IPv6 Hop-by-Hop Option'),
     1: ('icmp', 'Internet Control Message Protocol'),
     2: ('igmp', 'Internet Group Management Protocol'),
     3: ('ggp', 'Gateway-to-Gateway Protocol'),
     4: ('ipv4', 'IPv4 (encapsulation)'),
     5: ('st', 'Internet Stream Protocol'),
     6: ('tcp', 'Transmission Control Protocol'),
     7: ('cbt', 'Core-based trees'),
     8: ('egp', 'Exterior Gateway Protocol'),
     9: ('igp',
         'Interior Gateway Protocol (any private interior gateway (used by Cisco for their IGRP))'),
     10: ('bbn-rcc-mon', 'BBN RCC Monitoring'),
     11: ('nvp-ii', 'Network Voice Protocol'),
     12: ('pup', 'Xerox PUP'),
     13: ('argus', 'ARGUS'),
     14: ('emcon', 'EMCON'),
     15: ('xnet', 'Cross Net Debugger'),
     16: ('chaos', 'Chaos'),
     17: ('udp', 'User Datagram Protocol'),
     18: ('mux', 'Multiplexing'),
     19: ('dcn-meas', 'DCN Measurement Subsystems'),
     20: ('hmp', 'Host Monitoring Protocol'),
     21: ('prm', 'Packet Radio Measurement'),
     22: ('xns-idp', 'XEROX NS IDP'),
     23: ('trunk-1', 'Trunk-1'),
     24: ('trunk-2', 'Trunk-2'),
     25: ('leaf-1', 'Leaf-1'),
     26: ('leaf-2', 'Leaf-2'),
     27: ('rdp', 'Reliable Datagram Protocol'),
     28: ('irtp', 'Internet Reliable Transaction Protocol'),
     29: ('iso-tp4', 'ISO Transport Protocol Class 4'),
     30: ('netblt', 'Bulk Data Transfer Protocol'),
     31: ('mfe-nsp', 'MFE Network Services Protocol'),
     32: ('merit-inp', 'MERIT Internodal Protocol'),
     33: ('dccp', 'Datagram Congestion Control Protocol'),
     34: ('3pc', 'Third Party Connect Protocol'),
     35: ('idpr', 'Inter-Domain Policy Routing Protocol'),
     36: ('xtp', 'Xpress Transport Protocol'),
     37: ('ddp', 'Datagram Delivery Protocol'),
     38: ('idpr-cmtp', 'IDPR Control Message Transport Protocol'),
     39: ('tp++', 'TP++ Transport Protocol'),
     40: ('il', 'IL Transport Protocol'),
     41: ('ipv6', '6in4 (encapsulation)'),
     42: ('sdrp', 'Source Demand Routing Protocol'),
     43: ('ipv6-route', 'Routing Header for IPv6'),
     44: ('ipv6-frag', 'Fragment Header for IPv6'),
     45: ('idrp', 'Inter-Domain Routing Protocol'),
     46: ('rsvp', 'Resource Reservation Protocol'),
     47: ('gre', 'Generic Routing Encapsulation'),
     48: ('mhrp', 'Mobile Host Routing Protocol'),
     49: ('bna', 'BNA'),
     50: ('esp', 'Encapsulating Security Payload'),
     51: ('ah', 'Authentication Header'),
     52: ('i-nlsp', 'Integrated Net Layer Security Protocol'),
     53: ('swipe', 'SwIPe'),
     54: ('narp', 'NBMA Address Resolution Protocol'),
     55: ('mobile', 'IP Mobility (Min Encap)'),
     56: ('tlsp',
          'Transport Layer Security Protocol (using Kryptonet key management)'),
     57: ('skip', 'Simple Key-Management for Internet Protocol'),
     58: ('ipv6-icmp', 'ICMP for IPv6'),
     59: ('ipv6-nonxt', 'No Next Header for IPv6'),
     60: ('ipv6-opts', 'Destination Options for IPv6'),
     61: ('', 'Any host internal protocol'),
     62: ('cftp', 'CFTP'),
     63: ('', 'Any local network'),
     64: ('sat-expak', 'SATNET and Backroom EXPAK'),
     65: ('kryptolan', 'Kryptolan'),
     66: ('rvd', 'MIT Remote Virtual Disk Protocol'),
     67: ('ippc', 'Internet Pluribus Packet Core'),
     68: ('', 'Any distributed file system'),
     69: ('sat-mon', 'SATNET Monitoring'),
     70: ('visa', 'VISA Protocol'),
     71: ('ipcv', 'Internet Packet Core Utility'),
     72: ('cpnx', 'Computer Protocol Network Executive'),
     73: ('cphb', 'Computer Protocol Heart Beat'),
     74: ('wsn', 'Wang Span Network'),
     75: ('pvp', 'Packet Video Protocol'),
     76: ('br-sat-mon', 'Backroom SATNET Monitoring'),
     77: ('sun-nd', 'SUN ND PROTOCOL-Temporary'),
     78: ('wb-mon', 'WIDEBAND Monitoring'),
     79: ('wb-expak', 'WIDEBAND EXPAK'),
     80: ('iso-ip',
          'International Organization for Standardization Internet Protocol'),
     81: ('vmtp', 'Versatile Message Transaction Protocol'),
     82: ('secure-vmtp', 'Secure Versatile Message Transaction Protocol'),
     83: ('vines', 'VINES'),
     84: ('iptm', 'Internet Protocol Traffic Manager'),
     85: ('nsfnet-igp', 'NSFNET-IGP'),
     86: ('dgp', 'Dissimilar Gateway Protocol'),
     87: ('tcf', 'TCF'),
     88: ('eigrp', 'EIGRP'),
     89: ('ospf', 'Open Shortest Path First'),
     90: ('sprite-rpc', 'Sprite RPC Protocol'),
     91: ('larp', 'Locus Address Resolution Protocol'),
     92: ('mtp', 'Multicast Transport Protocol'),
     93: ('ax.25', 'AX.25'),
     94: ('ipip', 'IP-within-IP Encapsulation Protocol'),
     95: ('micp', 'Mobile Internetworking Control Protocol'),
     96: ('scc-sp', 'Semaphore Communications Sec. Pro'),
     97: ('etherip', 'Ethernet-within-IP Encapsulation'),
     98: ('encap', 'Encapsulation Header'),
     99: ('', 'Any private encryption scheme'),
     100: ('gmtp', 'GMTP'),
     101: ('ifmp', 'Ipsilon Flow Management Protocol'),
     102: ('pnni', 'PNNI over IP'),
     103: ('pim', 'Protocol Independent Multicast'),
     104: ('aris', "IBM's ARIS (Aggregate Route IP Switching) Protocol"),
     105: ('scps', 'SCPS (Space Communications Protocol Standards)'),
     106: ('qnx', 'QNX'),
     107: ('a/n', 'Active Networks'),
     108: ('ipcomp', 'IP Payload Compression Protocol'),
     109: ('snp', 'Sitara Networks Protocol'),
     110: ('compaq-peer', 'Compaq Peer Protocol'),
     111: ('ipx-in-ip', 'IPX in IP'),
     112: ('vrrp',
           'Virtual Router Redundancy Protocol, Common Address Redundancy Protocol'),
     113: ('pgm', 'PGM Reliable Transport Protocol'),
     114: ('', 'Any 0-hop protocol'),
     115: ('l2tp', 'Layer Two Tunneling Protocol Version 3'),
     116: ('ddx', 'D-II Data Exchange (DDX)'),
     117: ('iatp', 'Interactive Agent Transfer Protocol'),
     118: ('stp', 'Schedule Transfer Protocol'),
     119: ('srp', 'SpectraLink Radio Protocol'),
     120: ('uti', 'UTI'),
     121: ('smp', 'Simple Message Protocol'),
     122: ('sm', 'SM'),
     123: ('ptp', 'Performance Transparency Protocol'),
     124: ('', 'IS-IS over IPv4'),
     125: ('fire', ''),
     126: ('crtp', 'Combat Radio Transport Protocol'),
     127: ('crudp', 'Combat Radio User Datagram'),
     128: ('sscopmce', ''),
     129: ('iplt', ''),
     130: ('sps', 'Secure Packet Shield'),
     131: ('pipe', 'Private IP Encapsulation within IP'),
     132: ('sctp', 'Stream Control Transmission Protocol'),
     133: ('fc', 'Fibre Channel'),
     134: ('', 'RSVP-E2E-IGNORE'),
     135: ('', 'Mobility Header'),
     136: ('', 'UDP Lite'),
     137: ('', 'MPLS-in-IP'),
     138: ('manet', 'MANET Protocols'),
     139: ('hip', 'Host Identity Protocol'),
     140: ('shim6', 'Site Multihoming by IPv6 Intermediation'),
     141: ('unassigned', 'Unassigned'),
     142: ('unassigned', 'Unassigned'),
     143: ('unassigned', 'Unassigned'),
     144: ('unassigned', 'Unassigned'),
     145: ('unassigned', 'Unassigned'),
     146: ('unassigned', 'Unassigned'),
     147: ('unassigned', 'Unassigned'),
     148: ('unassigned', 'Unassigned'),
     149: ('unassigned', 'Unassigned'),
     150: ('unassigned', 'Unassigned'),
     151: ('unassigned', 'Unassigned'),
     152: ('unassigned', 'Unassigned'),
     153: ('unassigned', 'Unassigned'),
     154: ('unassigned', 'Unassigned'),
     155: ('unassigned', 'Unassigned'),
     156: ('unassigned', 'Unassigned'),
     157: ('unassigned', 'Unassigned'),
     158: ('unassigned', 'Unassigned'),
     159: ('unassigned', 'Unassigned'),
     160: ('unassigned', 'Unassigned'),
     161: ('unassigned', 'Unassigned'),
     162: ('unassigned', 'Unassigned'),
     163: ('unassigned', 'Unassigned'),
     164: ('unassigned', 'Unassigned'),
     165: ('unassigned', 'Unassigned'),
     166: ('unassigned', 'Unassigned'),
     167: ('unassigned', 'Unassigned'),
     168: ('unassigned', 'Unassigned'),
     169: ('unassigned', 'Unassigned'),
     170: ('unassigned', 'Unassigned'),
     171: ('unassigned', 'Unassigned'),
     172: ('unassigned', 'Unassigned'),
     173: ('unassigned', 'Unassigned'),
     174: ('unassigned', 'Unassigned'),
     175: ('unassigned', 'Unassigned'),
     176: ('unassigned', 'Unassigned'),
     177: ('unassigned', 'Unassigned'),
     178: ('unassigned', 'Unassigned'),
     179: ('unassigned', 'Unassigned'),
     180: ('unassigned', 'Unassigned'),
     181: ('unassigned', 'Unassigned'),
     182: ('unassigned', 'Unassigned'),
     183: ('unassigned', 'Unassigned'),
     184: ('unassigned', 'Unassigned'),
     185: ('unassigned', 'Unassigned'),
     186: ('unassigned', 'Unassigned'),
     187: ('unassigned', 'Unassigned'),
     188: ('unassigned', 'Unassigned'),
     189: ('unassigned', 'Unassigned'),
     190: ('unassigned', 'Unassigned'),
     191: ('unassigned', 'Unassigned'),
     192: ('unassigned', 'Unassigned'),
     193: ('unassigned', 'Unassigned'),
     194: ('unassigned', 'Unassigned'),
     195: ('unassigned', 'Unassigned'),
     196: ('unassigned', 'Unassigned'),
     197: ('unassigned', 'Unassigned'),
     198: ('unassigned', 'Unassigned'),
     199: ('unassigned', 'Unassigned'),
     200: ('unassigned', 'Unassigned'),
     201: ('unassigned', 'Unassigned'),
     202: ('unassigned', 'Unassigned'),
     203: ('unassigned', 'Unassigned'),
     204: ('unassigned', 'Unassigned'),
     205: ('unassigned', 'Unassigned'),
     206: ('unassigned', 'Unassigned'),
     207: ('unassigned', 'Unassigned'),
     208: ('unassigned', 'Unassigned'),
     209: ('unassigned', 'Unassigned'),
     210: ('unassigned', 'Unassigned'),
     211: ('unassigned', 'Unassigned'),
     212: ('unassigned', 'Unassigned'),
     213: ('unassigned', 'Unassigned'),
     214: ('unassigned', 'Unassigned'),
     215: ('unassigned', 'Unassigned'),
     216: ('unassigned', 'Unassigned'),
     217: ('unassigned', 'Unassigned'),
     218: ('unassigned', 'Unassigned'),
     219: ('unassigned', 'Unassigned'),
     220: ('unassigned', 'Unassigned'),
     221: ('unassigned', 'Unassigned'),
     222: ('unassigned', 'Unassigned'),
     223: ('unassigned', 'Unassigned'),
     224: ('unassigned', 'Unassigned'),
     225: ('unassigned', 'Unassigned'),
     226: ('unassigned', 'Unassigned'),
     227: ('unassigned', 'Unassigned'),
     228: ('unassigned', 'Unassigned'),
     229: ('unassigned', 'Unassigned'),
     230: ('unassigned', 'Unassigned'),
     231: ('unassigned', 'Unassigned'),
     232: ('unassigned', 'Unassigned'),
     233: ('unassigned', 'Unassigned'),
     234: ('unassigned', 'Unassigned'),
     235: ('unassigned', 'Unassigned'),
     236: ('unassigned', 'Unassigned'),
     237: ('unassigned', 'Unassigned'),
     238: ('unassigned', 'Unassigned'),
     239: ('unassigned', 'Unassigned'),
     240: ('unassigned', 'Unassigned'),
     241: ('unassigned', 'Unassigned'),
     242: ('unassigned', 'Unassigned'),
     243: ('unassigned', 'Unassigned'),
     244: ('unassigned', 'Unassigned'),
     245: ('unassigned', 'Unassigned'),
     246: ('unassigned', 'Unassigned'),
     247: ('unassigned', 'Unassigned'),
     248: ('unassigned', 'Unassigned'),
     249: ('unassigned', 'Unassigned'),
     250: ('unassigned', 'Unassigned'),
     251: ('unassigned', 'Unassigned'),
     252: ('unassigned', 'Unassigned'),
     253: ('testing', 'Experimentation and testing'),
     254: ('testing', 'Experimentation and testing'),
     255: ('reserved', 'Reserved')}

ICMP = \
    {0: {0: 'ping reply', 'name': 'Echo Reply'},
     1: {0: 'Reserved', 'name': 'Reserved'},
     2: {0: 'Reserved', 'name': 'Reserved'},
     3: {0: 'Destination network unreachable',
         1: 'Destination host unreachable',
         2: 'Destination protocol unreachable',
         3: 'Destination port unreachable',
         4: 'Fragmentation required, and DF flag set',
         5: 'Source route failed',
         6: 'Destination network unknown',
         7: 'Destination host unknown',
         8: 'Source host isolated',
         9: 'Network administratively prohibited',
         10: 'Host administratively prohibited',
         11: 'Network unreachable for TOS',
         12: 'Host unreachable for TOS',
         13: 'Communication administratively prohibited',
         14: 'Host Precedence Violation',
         15: 'Precedence cutoff in effect',
         'name': 'Destination Unreachable'},
     4: {0: 'Source quench (congestion control)', 'name': 'Source Quench'},
     5: {0: 'Redirect Datagram for the Network',
         1: 'Redirect Datagram for the Host',
         2: 'Redirect Datagram for the TOS & network',
         3: 'Redirect Datagram for the TOS & host',
         'name': 'Redirect Message'},
     6: {0: 'Alternate Host Address', 'name': 'Alternate Host Address'},
     7: {0: 'Reserved', 'name': 'Reserved'},
     8: {0: 'ping request', 'name': 'Echo Request'},
     9: {0: 'Router Advertisement', 'name': 'Router Advertisement'},
     10: {0: 'Router discovery/selection/solicitation',
          'name': 'Router Solicitation'},
     11: {0: 'TTL expired in transit',
          1: 'Fragment reassembly time exceeded',
          'name': 'Time Exceeded'},
     12: {0: 'Pointer indicates the error',
          1: 'Missing a required option',
          2: 'Bad length',
          'name': 'Parameter Problem: Bad IP header'},
     13: {0: 'Timestamp', 'name': 'Timestamp'},
     14: {0: 'Timestamp reply', 'name': 'Timestamp Reply'},
     15: {0: 'Information Request', 'name': 'Information Request'},
     16: {0: 'Information Reply', 'name': 'Information Reply'},
     17: {0: 'Address Mask Request', 'name': 'Address Mask Request'},
     18: {0: 'Address Mask Reply', 'name': 'Address Mask Reply'},
     19: {0: 'Reserved for security', 'name': 'Reserved'},
     20: {0: 'Reserved for robustness experiment', 'name': 'Reserved'},
     21: {0: 'Reserved for robustness experiment', 'name': 'Reserved'},
     22: {0: 'Reserved for robustness experiment', 'name': 'Reserved'},
     23: {0: 'Reserved for robustness experiment', 'name': 'Reserved'},
     24: {0: 'Reserved for robustness experiment', 'name': 'Reserved'},
     25: {0: 'Reserved for robustness experiment', 'name': 'Reserved'},
     26: {0: 'Reserved for robustness experiment', 'name': 'Reserved'},
     27: {0: 'Reserved for robustness experiment', 'name': 'Reserved'},
     28: {0: 'Reserved for robustness experiment', 'name': 'Reserved'},
     29: {0: 'Reserved for robustness experiment', 'name': 'Reserved'},
     30: {0: 'Information Request', 'name': 'Traceroute'},
     31: {0: 'Datagram Conversion Error', 'name': 'Error'},
     32: {0: 'Mobile Host Redirect', 'name': 'Mobile'},
     33: {0: 'Where-Are-You', 'name': 'SYN'},
     34: {0: 'Here-I-Am', 'name': 'ACK'},
     35: {0: 'Request', 'name': 'Mobile Registration'},
     36: {0: 'Reply', 'name': 'Mobile Registration'},
     37: {0: 'Request', 'name': 'Domain Name'},
     38: {0: 'Reply', 'name': 'Domain Name'},
     39: {0: 'SKIP Algorithm Discovery Protocol', 'name': 'SKIP'},
     40: {0: 'Security failures', 'name': 'Photuris'},
     41: {0: 'ICMP for experimental mobility protocols',
          'name': 'Mobile Experiment'}}
