# file: roles/GeoIP/tasks/GeoIP_install_tasks.yml

# ------------------------------------------------------------
# Build base Maxmind GeoIP lib
- name: Copy over GeoIP lib and unpack
  unarchive: src={{ GeoIP_lib_tgz }} dest={{ dependencies_root }}
  args:
    creates: "{{ GeoIP_lib_unarc }}"

- name: Build GeoIP lib
  shell: "{{ item }}"
  args:
    chdir: "{{ GeoIP_lib_unarc }}"
    creates: "{{ GeoIP_lib_sentinel }}"
  with_items:
    - "./configure --prefix={{ scape_distro_root|quote }}"
    - export LC_CTYPE=C && export LANG=C && make install
    
# ------------------------------------------------------------
# Build base Maxmind GeoIP lib

- name: Copy over GeoIP-Python and unpack
  unarchive: src={{ GeoIP_pyext_tgz }} dest={{ dependencies_root }}

- name: Build GeoIP-Python extension
  shell: "{{ pydist_build_ext_default }}"
  args:
    chdir: "{{ GeoIP_pyext_unarc }}"


