# file: roles/ant/tasks/ant_install_RedHat.yml

- name: Check for existence of ant
  shell: ant -version
  register: ant_installed
  ignore_errors: True
  
- name: Install ant packages
  apt: name={{ item }}
  sudo: yes
  with_items:
    - ant
    - ant-contrib
    - ant-optional
  when: ant_installed.rc != 0

